#! /usr/bin/env python

# Copyright (c) 2015, Fundacion Dr. Manuel Sadosky
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.

# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import print_function

import argparse
import os
import sys
import time

from barf.analysis.basicblock.callgraph import CallGraph
from barf.barf import BARF
from barf.core.symbols import load_symbols


def load_symbols_from_file(filename):
    symbols = {}

    with open(filename, "r") as f:
        for line in f.readlines():
            # Remove trailing '\n'.
            line = line[:-1]

            # Skip blank lines and comments.
            if (line == "" or line[0] == "#"):
                continue

            # Process line.
            parts = line.split(' ')

            try:
                addr, name, size, returns = parts[0], " ".join(parts[1:-2]), parts[-2], parts[-1]
            except:
                raise Exception("Error processing symbol file.")

            symbols[int(addr, 16)] = (name, int(size), returns == "True")

    return symbols

def recover_function_graph(barf, address, symbols):
    fn_name, fn_size, _ = symbols[address]
    fn_start = address
    fn_end = address + fn_size

    cfg, _ = barf.recover_cfg(ea_start=fn_start, ea_end=fn_end - 1, symbols=symbols)

    if len(cfg.basic_blocks) > 0:
        return cfg
    else:
        return None

def recover_function_graph_all(barf):
    def print_status(address):
        name = "sub_{:x}".format(address)

        print("    Processing {} @ {:#x}...".format(name, address))

    start = barf.binary.entry_point

    cfgs = barf.recover_cfg_all(start, callback=print_status)

    cfgs_final = []
    for addr, cfg in cfgs:
        if len(cfg.basic_blocks) > 0:
            cfgs_final.append(cfg)
    cfgs = cfgs_final

    return cfgs

def create_output_dir(name):
    if not os.path.exists(name):
        os.makedirs(name)

    return name

def init_parser():

    description = "Tool for recovering CG of a binary."

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=description)

    parser.add_argument(
        "filename",
        type=str,
        help="Binary file name.")

    parser.add_argument(
        "-s", "--symbol-file",
        type=str,
        help="Load symbols from file.")

    parser.add_argument(
        "-a", "--recover-all",
        action="store_true",
        help="Recover all functions.")

    parser.add_argument(
        "-t", "--time",
        action="store_true",
        help="Print process time.")

    return parser

def main():

    parser = init_parser()

    args = parser.parse_args()

    process_start = time.time()

    filename = os.path.abspath(args.filename)

    if not os.path.isfile(filename):
        print("[-] Error opening file : {}".format(filename))

        sys.exit(1)

    # Create an instance of BARF.
    try:
        barf = BARF(filename)
    except Exception:
        print("[-] Error opening file : {}".format(filename))

        sys.exit(1)

    output_dir = "."

    # Load symbols.
    print("[+] Parsing symbol table...")

    if args.symbol_file:
        symbols_by_addr = load_symbols_from_file(args.symbol_file)
    else:
        symbols = load_symbols(filename)

        symbols_by_addr = {
            addr : (name, size, True)
                for addr, size, name in symbols
        }

    symbols_by_name = {
        name : (addr, size, returns)
            for addr, (name, size, returns) in symbols_by_addr.items()
    }

    # Recover CFGs.
    print("[+] Recovering program CFGs...")

    if args.recover_all:
        if len(symbols_by_name) > 0:
            cfgs = []
            for addr in sorted(symbols_by_addr.keys()):
                name, size, _ = symbols_by_addr[addr]

                print("    Processing {} @ {:#x} ({})...".format(name, addr, size))

                cfg = recover_function_graph(barf, addr, symbols_by_addr)

                if cfg:
                    cfgs.append(cfg)
        else:
            cfgs = recover_function_graph_all(barf)

    # Recover CG.
    print("[+] Recovering program CG...")

    cg = CallGraph(cfgs)

    cg.save_ex(output_dir + os.path.sep + filename.split('/')[-1] + "_callgraph")

    process_end = time.time()

    if args.time:
        process_time = process_end - process_start

        print("[+] Process time: {:.3f}s".format(process_time))

if __name__ == "__main__":

    main()
